// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackItApp.Infrastructure.Implementations.Persistence;

#nullable disable

namespace TrackItApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251003060912_Create03")]
    partial class Create03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackItApp.Domain.Entities.DWConfidence", b =>
                {
                    b.Property<int>("ConfidenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfidenceID"));

                    b.Property<int>("ConfidenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ConfidencePeriod")
                        .HasColumnType("integer");

                    b.Property<int>("DictionaryID")
                        .HasColumnType("integer");

                    b.HasKey("ConfidenceID");

                    b.HasIndex("DictionaryID");

                    b.ToTable("DWConfidences");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DWDetail", b =>
                {
                    b.Property<int>("WordDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WordDetailID"));

                    b.Property<string>("Arabic")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WordID")
                        .HasColumnType("integer");

                    b.Property<string>("WordImage")
                        .HasColumnType("text");

                    b.HasKey("WordDetailID");

                    b.HasIndex("WordID");

                    b.ToTable("DWDetails");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DWReviewHistory", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("NewConfidenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("OldConfidenceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WordID")
                        .HasColumnType("integer");

                    b.HasKey("ReviewID");

                    b.HasIndex("WordID");

                    b.ToTable("DWReviewHistories");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.Dictionary", b =>
                {
                    b.Property<int>("DictionaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DictionaryID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("integer");

                    b.Property<string>("DictionaryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DictionaryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DictionaryID");

                    b.HasIndex("CreatedByUserID");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DictionaryWord", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WordID"));

                    b.Property<int?>("ConfidenceID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DictionaryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextReview")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pronunciation")
                        .HasColumnType("text");

                    b.Property<string>("Sources")
                        .HasColumnType("text");

                    b.Property<string>("WordText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("lastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WordID");

                    b.HasIndex("ConfidenceID");

                    b.HasIndex("DictionaryID");

                    b.ToTable("DictionaryWords");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("BackupEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("UserSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserSessionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("UserSessionID");

                    b.HasIndex("UserID", "DeviceID")
                        .IsUnique();

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTypeID"));

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserTypeID");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.VerificationCode", b =>
                {
                    b.Property<int>("VerificationCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerificationCodeID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CodeType")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("VerificationCodeID");

                    b.HasIndex("UserID", "DeviceID")
                        .IsUnique();

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DWConfidence", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.Dictionary", "Dictionary")
                        .WithMany("DictionaryWordConfidences")
                        .HasForeignKey("DictionaryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DWDetail", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.DictionaryWord", "DictionaryWord")
                        .WithMany("DictionaryWordDetails")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryWord");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DWReviewHistory", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.DictionaryWord", "DictionaryWord")
                        .WithMany("DictionaryReviewHistories")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryWord");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.Dictionary", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.User", "CreatedByUser")
                        .WithMany("Dictionaries")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DictionaryWord", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.DWConfidence", "DictionaryWordConfidence")
                        .WithMany("dictionaryWords")
                        .HasForeignKey("ConfidenceID");

                    b.HasOne("TrackItApp.Domain.Entities.Dictionary", "Dictionary")
                        .WithMany("DictionaryWords")
                        .HasForeignKey("DictionaryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");

                    b.Navigation("DictionaryWordConfidence");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.User", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.VerificationCode", b =>
                {
                    b.HasOne("TrackItApp.Domain.Entities.User", "User")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DWConfidence", b =>
                {
                    b.Navigation("dictionaryWords");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.Dictionary", b =>
                {
                    b.Navigation("DictionaryWordConfidences");

                    b.Navigation("DictionaryWords");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.DictionaryWord", b =>
                {
                    b.Navigation("DictionaryReviewHistories");

                    b.Navigation("DictionaryWordDetails");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Dictionaries");

                    b.Navigation("UserSessions");

                    b.Navigation("VerificationCodes");
                });

            modelBuilder.Entity("TrackItApp.Domain.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
